server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  apiDocs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled : 'true'

